baseURL = 'http://codeslides.gh.eddys.site/'
languageCode = 'en-us'
title = 'Code Slides'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
